# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     # vb.gui = true

     # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  config.vm.provision "shell", inline: "yum update -y"
  config.vm.provision "shell", inline: "yum install -y java-1.8.0-openjdk-devel"
  config.vm.provision "shell", inline: "yum install -y unzip"
  config.vm.provision "shell", inline: "echo 10.10.10.101 server1 >> /etc/hosts"
  config.vm.provision "shell", inline: "echo 10.10.10.102 server2 >> /etc/hosts"
  config.vm.provision "shell", inline: "cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
  config.vm.provision "shell", inline: "chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys"
  config.vm.provision "shell", inline: "cat /vagrant/id_rsa > /home/vagrant/.ssh/id_rsa"
  config.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/id_rsa"
  config.vm.provision "shell", inline: "chown vagrant:vagrant /home/vagrant/.ssh/id_rsa"
  config.vm.provision "file", source: "pivotal-gemfire-9.0.4.zip", destination: "/tmp/pivotal-gemfire-9.0.4.zip"
  config.vm.provision "shell", inline: "unzip -o /tmp/pivotal-gemfire-9.0.4.zip -d /home/vagrant"
  config.vm.provision "shell", inline: "chown vagrant:vagrant -R /home/vagrant/pivotal-gemfire-9.0.4"
  config.vm.provision "shell", inline: "mkdir -p /home/vagrant/gemfire_cluster"
  config.vm.provision "shell", inline: "mkdir -p /home/vagrant/gemfire_cluster/logs"
  config.vm.provision "shell", inline: "mkdir -p /home/vagrant/gemfire_cluster/data"
  config.vm.provision "shell", inline: "mkdir -p /home/vagrant/gemfire_cluster/backups"
  config.vm.provision "shell", inline: "chown vagrant:vagrant -R /home/vagrant/gemfire_cluster"
  config.vm.provision "file", source: "trusted.keystore", destination: "/home/vagrant/gemfire_cluster/trusted.keystore"
  config.vm.provision "file", source: "security.properties", destination: "/home/vagrant/gemfire_cluster/security.properties"

  config.vm.define "server1" do |server1|
     server1.vm.network "private_network", ip: "10.10.10.101"
     server1.vm.provision "shell", inline: "hostname server1", run: "always"
  end

  config.vm.define "server2" do |server2|
    server2.vm.network "private_network", ip: "10.10.10.102"
    server2.vm.provision "shell", inline: "hostname server2", run: "always"
  end

end
